# Optimize OCS Qubit

## Read All the Data into DataFrame

In [122]:
import glob
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [123]:
data_files = glob.glob("data/*csv")
data_files

['data/simulation_info_2022-11-16-21-40-28.csv',
 'data/simulation_info_2022-11-17-12-33-05.csv',
 'data/simulation_info_2022-11-17-12-24-22.csv',
 'data/simulation_info_2022-11-16-21-55-23.csv',
 'data/simulation_info_2022-11-17-11-48-43.csv',
 'data/simulation_info_2022-11-16-21-33-00.csv',
 'data/simulation_info_2022-11-17-12-04-54.csv',
 'data/simulation_info_2022-11-16-21-44-12.csv',
 'data/simulation_info_2022-11-17-12-18-34.csv',
 'data/simulation_info_2022-11-16-21-25-29.csv',
 'data/simulation_info_2022-11-17-11-58-08.csv',
 'data/simulation_info_2022-11-16-21-47-55.csv',
 'data/simulation_info_2022-11-17-12-35-39.csv',
 'data/simulation_info_2022-11-16-21-29-14.csv',
 'data/simulation_info_2022-11-17-11-16-14.csv',
 'data/simulation_info_2022-11-17-12-27-28.csv',
 'data/simulation_info_2022-11-17-12-29-39.csv',
 'data/simulation_info_2022-11-17-12-11-29.csv',
 'data/simulation_info_2022-11-16-21-36-44.csv',
 'data/simulation_info_2022-11-17-12-03-00.csv',
 'data/simulation_in

In [124]:
dfs = [pd.read_csv(data_files[i]) for i in range(len(data_files))]

In [125]:
df = pd.concat(dfs)
df

Unnamed: 0  cross_length (um)  cross_width (um)  cross_gap (um)  Lj (nH)  \
0           0                225                30              30       60   
0           0                130                10              35       20   
0           0                130                40              20       20   
0           0                225                30              30      100   
0           0                100                50              20       20   
0           0                225                30              30       40   
0           0                100                10              50       20   
0           0                225                30              30       70   
0           0                130                20              20       20   
0           0                225                30              30       20   
0           0                100                30              35       20   
0           0                225                30              30       80   
0           0                130                20              35       20   
0           0                225                30              30       30   
0           0                150                25              40       40   
0           0                130                50              20       20   
0           0                130                60              20       20   
0           0                100                50              50       20   
0           0                225                30              30       50   
0           0                100                60              35       20   
0           0                100                25              40       20   
0           0                225                30              30       40   
0           0                100                60              50       20   
0           0                100                40              35       20   
0           0                100                20              35       20   
0           0                225                30              30       10   
0           0                100                30              20       20   
0           0                100                10              35       20   
0           0                100                60              20       20   
0           0                100                20              20       20   
0           0                100                40              50       20   
0           0                225                30              30       90   
0           0                130                10              20       20   
0           0                100                20              50       20   
0           0                100                30              50       20   
0           0                100                50              35       20   
0           0                150                25              40       20   
0           0                100                10              20       20   
0           0                225                30              30       20   
0           0                200                25              40       20   
0           0                100                40              20       20   
0           0                225                30              30       30   
0           0                225                30              30       10   
0           0                130                30              20       20   

   Cj (fF)  qubit_freq (GHz)        ratio  alpha (MHz)  w03 (GHz)  
0    32.72          4.474118    18.545471  -881.409316  11.659536  
0   127.48          7.017556    22.324282  -732.213965  19.588240  
0   127.48          5.415701    37.023574  -441.506572  15.364089  
0    11.65          4.474118  1129.535827   -14.471565  13.393412  
0   127.48          6.040630    29.657683  -551.160766  17.019568  
0    56.71          4.474118    27.7436

# OCS Qubit Analysis:

## Constraint 1: $\frac{E_j}{E_c} \le 20$

In [130]:
df1 = df[df["ratio"] <= 20]
df1

Unnamed: 0  cross_length (um)  cross_width (um)  cross_gap (um)  Lj (nH)  \
0           0                225                30              30       60   
0           0                100                10              50       20   
0           0                150                25              40       40   
0           0                100                10              35       20   
0           0                100                20              50       20   
0           0                100                10              20       20   

   Cj (fF)  qubit_freq (GHz)      ratio  alpha (MHz)  w03 (GHz)  
0    32.72          4.474118  18.545471  -881.409316  11.659536  
0   127.48          8.363161  15.708265 -1040.608343  23.008266  
0    56.71          5.918278  15.758939 -1037.262172  15.680309  
0   127.48          8.038629  16.927161  -965.675863  22.184536  
0   127.48          7.684031  18.565521  -880.457447  21.291178  
0   127.48          7.432039  19.699080  -829.792605  20.636532

## Constraint 2: Smallest Qubit Frequency  (Ideally $\omega_{01} < 4$ )

In [131]:
df1 = df1.sort_values(by=['qubit_freq (GHz)'])
df1

Unnamed: 0  cross_length (um)  cross_width (um)  cross_gap (um)  Lj (nH)  \
0           0                225                30              30       60   
0           0                150                25              40       40   
0           0                100                10              20       20   
0           0                100                20              50       20   
0           0                100                10              35       20   
0           0                100                10              50       20   

   Cj (fF)  qubit_freq (GHz)      ratio  alpha (MHz)  w03 (GHz)  
0    32.72          4.474118  18.545471  -881.409316  11.659536  
0    56.71          5.918278  15.758939 -1037.262172  15.680309  
0   127.48          7.432039  19.699080  -829.792605  20.636532  
0   127.48          7.684031  18.565521  -880.457447  21.291178  
0   127.48          8.038629  16.927161  -965.675863  22.184536  
0   127.48          8.363161  15.708265 -1040.608343  23.008266

In [94]:
df2 = df1[df1["qubit_freq (GHz)"] < 4]
df2

Empty DataFrame
Columns: [Unnamed: 0, cross_length (um), cross_width (um), cross_gap (um), Lj (nH), Cj (fF), qubit_freq (GHz), ratio, alpha (MHz), w03 (GHz)]
Index: []

# Choose Qubit Parameters:

- **LL FIXES THE JJ LENGTH = 2 nm**

- [ ] get $L_j$
- [ ] COMPUTE JJ WIDTH FOR THE CORRESPONDING $L_j$

In [ ]:
L_j = None #from df
cross_length = None #from df
cross_width = None #from df
cross_gap = None #from df
w03 = None #from df

In [103]:
def compute_JJ_area(Lj):
    raise NotImplementedError()
    
def cal_josephson_inductance(jj_length, density = 1, bSquid=False):
    jj_length = jj_length * 1e-3
    jj_width = 200 * 1e-3 # in um
    jj_area = jj_width * jj_length
    Ic = jj_area * density * 1e-6  # in uA
    pi = np.pi
    Phi0 = 2.068 * 1e-15
    if not bSquid:
        return Phi0/Ic/2/pi * 1e9 #in nH
    else:
        return Phi0/(Ic*2)/2/pi * 1e9
    
def cal_JJ_width(Lj, density = 1, bSquid=False):
    Lj = Lj * 1E-9 #in puts in nH -> converts to base unit
    jj_length = 200 * 1e-3 # in um
    pi = np.pi
    Phi0 = 2.068 * 1e-15
    if not bSquid:
        return Phi0 / (2 * pi * jj_length * density * Lj) * 1E9 #nm
    else:
        return Phi0/ (4 * pi * jj_length * density * Lj) * 1E9 #nm

In [140]:
jj_width = cal_JJ_width(10.9, bSquid=False)
jj_width

150.97817537341263

In [210]:
cal_josephson_inductance(150, density = 1, bSquid=False)

10.97108074380132

In [211]:
cross_lengths = np.arange(100,200,25)
cross_widths = np.arange(5,30,5)
cross_gaps = np.arange(35,51,5)


In [212]:
len(cross_lengths)*len(cross_widths)*len(cross_gaps)*4/60

5.333333333333333

In [213]:
cross_lengths

array([100, 125, 150, 175])

In [214]:
cross_widths

array([ 5, 10, 15, 20, 25])

In [215]:
cross_gaps

array([35, 40, 45, 50])